// Copyright (c) RoochNetwork
// SPDX-License-Identifier: Apache-2.0

pub mod account_authentication;
/// Types mapping from Framework Move types to Rust types
/// Module binding for the Framework
//TODO there modules maybe generated by ABI in the future
pub mod address_mapping;
pub mod auth_validator;
pub mod bitcoin_validator;
pub mod coin;
pub mod empty;
pub mod ethereum_validator;
pub mod genesis;
pub mod native_validator;
pub mod nostr_validator;
pub mod session_key;
pub mod transaction_validator;

/// MoveOS system pre_execute functions registry.
/// The registry is used to filter out system pre_execute functions.
/// All system pre_execute functions are called before other pre_execute functions.
/// TODO: is there a better way to construct this registry? Should we register
/// system pre_execute functions on-chain and dynamically?
static SYSTEM_PRE_EXECUTE_FUNCTIONS: Lazy<[FunctionCall]> =
    Lazy::new(|| [TransactionValidator::pre_execute_function_call()]);

/// MoveOS system post_execute functions registry.
/// The registry is used to filter out system post_execute functions.
/// All system post_execute functions are called after other post_execute functions.
/// TODO: is there a better way to construct this registry? Should we register
/// system pre_execute functions on-chain and dynamically?
static SYSTEM_POST_EXECUTE_FUNCTIONS: Lazy<[FunctionCall]> =
    Lazy::new(|| [TransactionValidator::post_execute_function_call()]);
