// This file was generated by `yarn gen:client`. Please, do not modify it.
export type AnnotatedEventView = {
  event: EventView;
  parsed_event_data: AnnotatedMoveStructView;
  sender: AccountAddress;
  timestamp_ms?: number | null;
  tx_hash?: Hex | null;
};

export type AnnotatedFunctionReturnValueView = {
  move_value: AnnotatedMoveValueView;
  value: FunctionReturnValueView;
};

export type AnnotatedMoveStructView = {
  abilities: number;
  type: StructTag;
  value: { [key: string]: AnnotatedMoveValueView };
};

export type AnnotatedMoveValueView =
  | number
  | unknown
  | u128
  | boolean
  | AccountAddress
  | AnnotatedMoveValueView[]
  | Uint8Array
  | AnnotatedMoveStructView
  | SpecificStructView
  | number
  | number
  | U256;

export type AnnotatedStateView = {
  move_value: AnnotatedMoveValueView;
  state: StateView;
};

export type AuthenticatorView = { payload: Uint8Array; scheme: u64 };

export type EventFilterView0 = { Sender: AccountAddress };

export type EventFilterView1 = { Transaction: Hex };

export type EventFilterView2 = { MoveEventType: TypeTag };

export type EventFilterView3 = {
  MoveEventField: { path: string; value: true };
};

export type EventFilterView4 = {
  TimeRange: { end_time: number; start_time: number };
};

export type EventFilterView5 = { All: EventFilterView[] };

export type EventFilterView6 = { Any: EventFilterView[] };

export type EventFilterView7 = { And: unknown[] };

export type EventFilterView8 = { Or: unknown[] };

export type EventFilterView =
  | EventFilterView0
  | EventFilterView1
  | EventFilterView2
  | EventFilterView3
  | EventFilterView4
  | EventFilterView5
  | EventFilterView6
  | EventFilterView7
  | EventFilterView8;

export type EventID = { event_handle_id: unknown; event_seq: number };

export type EventView = {
  event_data: Uint8Array;
  event_id: EventID;
  event_index: number;
  type_tag: TypeTag;
};

export type ExecuteTransactionResponseView = {
  execution_info: TransactionExecutionInfoView;
  output: TransactionOutputView;
  sequence_info: TransactionSequenceInfoView;
};

export type FunctionCallView = {
  args: Uint8Array[];
  function_id: FunctionId;
  ty_args: TypeTag[];
};

export type FunctionReturnValueView = { type_tag: TypeTag; value: Uint8Array };

// Missing properties and type: H256View

export type Hex = string;

export type KeptVMStatusView0 = { type: string };

export type KeptVMStatusView1 = { type: string };

export type KeptVMStatusView2 = {
  abort_code: u64;
  location: AbortLocation;
  type: string;
};

export type KeptVMStatusView3 = {
  code_offset: number;
  function: number;
  location: AbortLocation;
  type: string;
};

export type KeptVMStatusView4 = { type: string };

export type KeptVMStatusView =
  | KeptVMStatusView0
  | KeptVMStatusView1
  | KeptVMStatusView2
  | KeptVMStatusView3
  | KeptVMStatusView4;

export type MoveActionTypeView = string;

export type MoveActionView = {
  function_call?: FunctionCallView | null;
  module_bundle?: Uint8Array[] | null;
  script_call?: ScriptCallView | null;
};

export type MoveAsciiString = { bytes: number[] };

export type MoveString = { bytes: number[] };

// Missing properties and type: ObjectID

export type OpView_for_StateView0 = {
  type: string;
  value: Uint8Array;
  value_type: TypeTag;
};

export type OpView_for_StateView1 = {
  type: string;
  value: Uint8Array;
  value_type: TypeTag;
};

export type OpView_for_StateView2 = { type: string };

export type OpView_for_StateView =
  | OpView_for_StateView0
  | OpView_for_StateView1
  | OpView_for_StateView2;

export type PageView_for_Nullable_AnnotatedEventView_and_uint64 = {
  data: AnnotatedEventView | null[];
  has_next_page: boolean;
  next_cursor?: number | null;
};

export type PageView_for_Nullable_TransactionExecutionInfoView_and_uint128 = {
  data: TransactionExecutionInfoView | null[];
  has_next_page: boolean;
  next_cursor?: number | null;
};

export type ScriptCallView = {
  args: Uint8Array[];
  code: Uint8Array;
  ty_args: TypeTag[];
};

export type SpecificStructView = MoveString | MoveAsciiString | Hex;

export type StateChangeSetView = {
  changes: { [key: string]: TableChangeView };
  new_tables: { [key: string]: TableTypeInfoView };
  removed_tables: Hex[];
};

export type StateView = { value: Uint8Array; value_type: TypeTag };

export type TableChangeView = {
  entries: { [key: string]: OpView_for_StateView };
};

export type TableTypeInfoView = { key_type: TypeTag };

export type TransactionExecutionInfoView = {
  event_root: Hex;
  gas_used: number;
  state_root: Hex;
  status: KeptVMStatusView;
  tx_hash: Hex;
};

export type TransactionOutputView = {
  events: EventView[];
  gas_used: number;
  status: KeptVMStatusView;
  table_changeset: StateChangeSetView;
};

export type TransactionSequenceInfoView = {
  tx_accumulator_root: Hex;
  tx_order: u128;
  tx_order_signature: AuthenticatorView;
};

export type TransactionTypeView = string;

export type TransactionView = {
  action: MoveActionView;
  action_type: MoveActionTypeView;
  raw: Uint8Array;
  sender: string;
  sequence_number: number;
  transaction_type: TransactionTypeView;
};

export type AccountAddress = string;

export type StructTag = string;

export type TypeTag = string;

export type U256 = string;

export type AbortLocation = string;

export type AccessPath = string;

export type FunctionId = string;

export type u128 = string;

export type u64 = string;

// This file was generated by `yarn gen:client`. Please, do not modify it.