[package]
name = "gas_market"
version = "0.0.1"

[dependencies]
MoveStdlib = { local = "../../../../frameworks/move-stdlib" }
MoveosStdlib = { local = "../../../../frameworks/moveos-stdlib" }
RoochFramework = { local = "../../../../frameworks/rooch-framework" }
BitcoinMove = { local = "../../../../frameworks/bitcoin-move" }


[addresses]
gas_market = "_"
std = "0x1"
moveos_std = "0x2"
rooch_framework = "0x3"
bitcoin_move =  "0x4"
