apiVersion: v1
kind: Service
metadata:
  name: testnet-faucet-service
  namespace: testnet
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 6868
  selector:
    app: testnet-faucet