apiVersion: apps/v1
kind: Deployment
metadata:
  name: testnet-tweet-fetch-schedule
  namespace: testnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testnet-tweet-fetch-schedule
  template:
    metadata:
      labels:
        app: testnet-tweet-fetch-schedule
    spec:
      initContainers:
      - name: init-rooch
        image: ghcr.io/rooch-network/rooch:v0.8.4
        command: ["/bin/sh", "-c"]
        args:
        - |
          if [ ! -f /root/.rooch/initialized ]; then
            /rooch/rooch init -m "${INIT_SECRET}" --skip-password
            /rooch/rooch env switch --alias test
            /rooch/rooch account create
            /rooch/rooch account create
            /rooch/rooch account create
            /rooch/rooch account create
            /rooch/rooch account create
            ls -la /root/.rooch/rooch_config/
            touch /root/.rooch/initialized
          fi
        env:
        - name: INIT_SECRET
          valueFrom:
            secretKeyRef:
              name: rooch-testnet-secrets
              key: init-phrase
        volumeMounts:
        - name: rooch-data
          mountPath: /root
      containers:
      - name: rooch-schedule
        image: ghcr.io/rooch-network/rooch:v0.8.4
        command: ["/rooch/rooch"]
        args: 
        - "task"
        - "schedule"
        - "--sender"
        # the sixth account
        - "rooch1nf590t0ynzcd6xgkwka4pjt044sdc8f398qgra64vu4w4f20v2gq0v7t8w"
        - "--checker-function"
        - "0x701c21bf1c8cd5af8c42983890d8ca55e7a820171b8e744c13f2d9998bf76cc3::tweet_fetcher::has_buffered_tweets"
        - "--runner-function"
        - "0x701c21bf1c8cd5af8c42983890d8ca55e7a820171b8e744c13f2d9998bf76cc3::tweet_fetcher::process_buffer_queue"
        - "--checker-interval"
        - "60"
        volumeMounts:
        - name: rooch-data
          mountPath: /root
      volumes:
      - name: rooch-data
        persistentVolumeClaim:
          claimName: testnet-tweet-fetch-schedule-data