apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: testnet-gas-market-schedule-data
  namespace: testnet
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi