apiVersion: apps/v1
kind: Deployment
metadata:
  name: testnet-gas-market-schedule
  namespace: testnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testnet-gas-market-schedule
  template:
    metadata:
      labels:
        app: testnet-gas-market-schedule
    spec:
      initContainers:
      - name: init-rooch
        image: ghcr.io/rooch-network/rooch:v0.8.0
        command: ["/bin/sh", "-c"]
        args:
        - |
          if [ ! -f /root/.rooch/initialized ]; then
            /rooch/rooch init -m "${INIT_SECRET}" --skip-password
            /rooch/rooch env switch --alias test
            /rooch/rooch account create
            /rooch/rooch account create
            /rooch/rooch account create
            /rooch/rooch account create
            ls -la /root/.rooch/rooch_config/
            touch /root/.rooch/initialized
          fi
        env:
        - name: INIT_SECRET
          valueFrom:
            secretKeyRef:
              name: rooch-testnet-secrets
              key: init-phrase
        volumeMounts:
        - name: rooch-data
          mountPath: /root
      containers:
      - name: rooch-schedule
        image: ghcr.io/rooch-network/rooch:v0.8.0
        command: ["/rooch/rooch"]
        args: 
        - "task"
        - "schedule"
        - "--sender"
        # the five account
        - "rooch1cqqagzda3lsegvz73yp0ga5hppsmpegw06uyusexte4c7fhxg5qqd9x6mw"
        - "--checker-function"
        - "0x701c21bf1c8cd5af8c42983890d8ca55e7a820171b8e744c13f2d9998bf76cc3::gas_market::exists_new_events"
        - "--checker-args"
        - "object:0xdd83de197cc2f4829fc5004ce2a0cb1905601eac24a3f11a1e9c99a926c3dab2"
        - "--runner-function"
        - "0x701c21bf1c8cd5af8c42983890d8ca55e7a820171b8e744c13f2d9998bf76cc3::gas_market::consume_event"
        - "--runner-args"
        - "object:0xdd83de197cc2f4829fc5004ce2a0cb1905601eac24a3f11a1e9c99a926c3dab2"
        - "--checker-interval"
        - "5"
        volumeMounts:
        - name: rooch-data
          mountPath: /root
      volumes:
      - name: rooch-data
        persistentVolumeClaim:
          claimName: testnet-gas-market-schedule-data