packages:
#  - 'infra/dashboard/**'
  - 'infra/rooch-portal-v2/**'
#  - 'grow-rooch/**'
  - 'sdk/typescript/build-scripts'
  - 'sdk/typescript/rooch-sdk'
  - 'sdk/typescript/rooch-sdk-kit'
  - 'sdk/typescript/rooch-sdk-tg-kit'
  - 'sdk/typescript/templates/**'
  - 'sdk/typescript/rooch-create'
  - 'sdk/typescript/bitseed-sdk'
  - 'sdk/typescript/test-suite'
  - 'docs/**'
