packages:
  - 'infra/dashboard/**'
  - 'infra/rooch-portal/**'
  - 'grow-rooch/**'
  - 'sdk/typescript/build-scripts'
  - 'sdk/typescript/rooch-sdk'
  - 'sdk/typescript/rooch-sdk-kit'
  - 'sdk/typescript/templates/**'
  - 'sdk/typescript/rooch-create'
  - 'docs/**'
