[package]
name = "wasm_execution"
version = "0.0.1"

[dependencies]
MoveosStdlib = { local = "../../frameworks/moveos-stdlib" }
BitcoinMove = { local = "../../frameworks/bitcoin-move" }

[addresses]
rooch_examples =  "_"
moveos_std =  "0x2"
rooch_framework =  "0x3"
bitcoin_move = "0x4"

[dev-addresses]
rooch_examples = "0x42"
