[package]
name = "basic_object"
version = "0.0.1"

[dependencies]
MoveosStdlib = { local = "../../moveos/moveos-stdlib/moveos-stdlib" }

[addresses]
basic_object =  "_"
moveos_std =  "0x2"
rooch_framework =  "0x3"

[dev-addresses]
basic_object = "0x42"
