[package]
name = "nostr"
version = "0.0.1"

[dependencies]
MoveStdlib = { local = "../../frameworks/move-stdlib" }
MoveosStdlib = { local = "../../frameworks/moveos-stdlib" }
RoochFramework = { local = "../../frameworks/rooch-framework" }
RoochNursery = { local = "../../frameworks/rooch-nursery" }

[addresses]
std = "0x1"
moveos_std = "0x2"
rooch_framework = "0x3"
rooch_nursery = "0xa"
nostr = "_"

[dev-addresses]
nostr = "0x42"
