[package]
name = "rooch-test-transaction-builder"
version = "0.5.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true }
serde_yaml = { workspace = true }
serde_json = { workspace = true }
log = { workspace = true }
once_cell = { workspace = true }
bcs = { workspace = true }
fastcrypto = { workspace = true }

move-core-types = { workspace = true }
move-resource-viewer = { workspace = true }
move-binary-format = { workspace = true }
move-bytecode-utils = { workspace = true }
move-compiler = { workspace = true }
move-coverage = { workspace = true }
move-package = { workspace = true }


moveos-store = { workspace = true }
moveos-stdlib = { workspace = true }
framework-builder = { workspace = true }
moveos = { workspace = true }
moveos-types = { workspace = true }
moveos-verifier = { workspace = true }
raw-store = { workspace = true }
moveos-config = { workspace = true }
moveos-compiler = { workspace = true }

rooch-config = { workspace = true }
rooch-types ={ workspace = true }
rooch-framework = { workspace = true }
rooch-genesis = { workspace = true }
rooch-rpc-client = { workspace = true }
rooch-key = { workspace = true }


