[package]
name = "moveos-common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true }
serde_yaml = { workspace = true }
jsonrpsee = { workspace = true }
thiserror = { workspace = true }
tonic = { workspace = true }
coerce = { workspace = true }

moveos-types = { workspace = true }