processed 2 tasks

task 1 'publish'. lines 3-28:
Error: error: The struct test::AllowedStruct must have the 'copy' and 'drop' ability
   ┌─ /tmp/tempfile:10:5
   │  
10 │ ╭     struct AllowedStruct {
11 │ │        f_u64: u64,
12 │ │        f_address: address,
13 │ │        f_bool: bool,
14 │ │        f_str: std::string::String,
15 │ │        f_custom: Inner,
16 │ │     }
   │ ╰─────^

error: The type argument 0x42::test::AllowedStruct of #[data_struct] for function test::f2 in the module 0x42::test is not allowed.
   ┌─ /tmp/tempfile:20:5
   │  
20 │ ╭     public fun f2() {
21 │ │         f1<AllowedStruct>();
22 │ │     }
   │ ╰─────^


