processed 2 tasks

task 1 'publish'. lines 3-25:
Error: error: The struct test1::DisallowedStruct must have the 'copy' and 'drop' ability
   ┌─ /tmp/tempfile:9:5
   │  
 9 │ ╭     struct DisallowedStruct has drop{
10 │ │         value: NonDataStruct,
11 │ │     }
   │ ╰─────^

error: The type argument 0x42::test1::DisallowedStruct of #[data_struct] for function test1::f2 in the module 0x42::test1 is not allowed.
   ┌─ /tmp/tempfile:15:5
   │  
15 │ ╭     public fun f2(_ctx: &mut Context) {
16 │ │         let disallowed_struct = DisallowedStruct {
17 │ │             value: NonDataStruct {},
18 │ │         };
19 │ │         f1<DisallowedStruct>(disallowed_struct);
20 │ │     }
   │ ╰─────^


