[package]
name = "display"
version = "0.0.1"

[dependencies]
MoveStdlib = { local = "../../moveos/moveos-stdlib/move-stdlib" }
MoveosStdlib = { local = "../../moveos/moveos-stdlib/moveos-stdlib" }
RoochFramework = { local = "../../crates/rooch-framework" }

[addresses]
display =  "_"
std =  "0x1"
moveos_std =  "0x2"
rooch_framework =  "0x3"

[dev-addresses]
display = "0x42"
std =  "0x1"
moveos_std =  "0x2"
rooch_framework =  "0x3"