[package]
name = "move_v2"
version = "0.0.1"

[dependencies]
MoveStdlib = { local = "../../frameworks/move-stdlib" }
MoveosStdlib = { local = "../../frameworks/moveos-stdlib" }
RoochFramework = { local = "../../frameworks/rooch-framework" }
RoochNursery = { local = "../../frameworks/rooch-nursery" }

[addresses]
rooch_examples =  "_"
moveos_std =  "0x2"
rooch_framework =  "0x3"

[dev-addresses]
rooch_examples = "0x42"
