// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module rooch_examples::article_added_to_blog {

    use moveos_std::object_id::ObjectID;
    use rooch_examples::blog::{Self, ArticleAddedToBlog};

    public fun article_id(article_added_to_blog: &ArticleAddedToBlog): ObjectID {
        blog::article_added_to_blog_article_id(article_added_to_blog)
    }

}
