// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module rooch_examples::article_deleted {

    use moveos_std::object_id::ObjectID;
    use rooch_examples::article::{Self, ArticleDeleted};

    public fun id(article_deleted: &ArticleDeleted): ObjectID {
        article::article_deleted_id(article_deleted)
    }

}
