// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module rooch_examples::article_removed_from_blog {

    use moveos_std::object_id::ObjectID;
    use rooch_examples::blog::{Self, ArticleRemovedFromBlog};

    public fun article_id(article_removed_from_blog: &ArticleRemovedFromBlog): ObjectID {
        blog::article_removed_from_blog_article_id(article_removed_from_blog)
    }

}
