// Copyright (c) RoochNetwork
// SPDX-License-Identifier: Apache-2.0

// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module rooch_examples::article_aggregate {
    use moveos_std::object_id::ObjectID;
    
    use rooch_examples::article;
    use rooch_examples::article_add_comment_logic;
    use rooch_examples::article_create_logic;
    use rooch_examples::article_delete_logic;
    use rooch_examples::article_remove_comment_logic;
    use rooch_examples::article_update_comment_logic;
    use rooch_examples::article_update_logic;
    use std::string::String;

    public entry fun update_comment(
        
        account: &signer,
        id: ObjectID,
        comment_seq_id: u64,
        commenter: String,
        body: String,
        owner: address,
    ) {
        let article_obj = article::get_article_mut(id);
        let comment_updated = article_update_comment_logic::verify(
            account,
            comment_seq_id,
            commenter,
            body,
            owner,
            article_obj,
        );
        article_update_comment_logic::mutate(
            account,
            &comment_updated,
            article_obj,
        );
        article::update_version(article_obj);
        article::emit_comment_updated(comment_updated);
    }

    public entry fun remove_comment(
        
        account: &signer,
        id: ObjectID,
        comment_seq_id: u64,
    ) {
        let article_obj = article::get_article_mut(id);
        let comment_removed = article_remove_comment_logic::verify(
            account,
            comment_seq_id,
            article_obj,
        );
        article_remove_comment_logic::mutate(
            account,
            &comment_removed,
            article_obj,
        );
        article::update_version(article_obj);
        article::emit_comment_removed(comment_removed);
    }

    public entry fun add_comment(
        
        account: &signer,
        id: ObjectID,
        commenter: String,
        body: String,
    ) {
        let article_obj = article::get_article_mut(id);
        let comment_added = article_add_comment_logic::verify(
            account,
            commenter,
            body,
            article_obj,
        );
        article_add_comment_logic::mutate(
            account,
            &comment_added,
            article_obj,
        );
        article::update_version(article_obj);
        article::emit_comment_added(comment_added);
    }

    public entry fun create(
        
        account: &signer,
        title: String,
        body: String,
    ) {
        let article_created = article_create_logic::verify(
            
            account,
            title,
            body,
        );
        let article_id = article_create_logic::mutate(
            
            account,
            &article_created,
        );
        article::set_article_created_id(&mut article_created, article_id);
        article::emit_article_created(article_created);
    }

    public entry fun update(
        
        account: &signer,
        id: ObjectID,
        title: String,
        body: String,
    ) {
        let article_obj = article::get_article_mut(id);
        let article_updated = article_update_logic::verify(
            account,
            title,
            body,
            article_obj,
        );
        article_update_logic::mutate(
            account,
            &article_updated,
            article_obj,
        );
        article::update_version(article_obj);
        article::emit_article_updated(article_updated);
    }

    public entry fun delete(
        
        account: &signer,
        id: ObjectID,
    ) {
        let article_obj = article::get_article(id);
        let article_deleted = article_delete_logic::verify(
            account,
            article_obj,
        );
        let updated_article_obj = article_delete_logic::mutate(
            account,
            &article_deleted,
            id,
        );
        article::drop_article(updated_article_obj);
        article::emit_article_deleted(article_deleted);
    }

}
