// Copyright (c) RoochNetwork
// SPDX-License-Identifier: Apache-2.0

// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module rooch_examples::article_created {

    use moveos_std::object::ObjectID;
    use rooch_examples::article::{Self, ArticleCreated};
    use std::option;
    use std::string::String;

    public fun id(article_created: &ArticleCreated): option::Option<ObjectID> {
        article::article_created_id(article_created)
    }

    public fun title(article_created: &ArticleCreated): String {
        article::article_created_title(article_created)
    }

    public fun body(article_created: &ArticleCreated): String {
        article::article_created_body(article_created)
    }

}
