// Copyright (c) RoochNetwork
// SPDX-License-Identifier: Apache-2.0

// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module rooch_examples::article_aggregate {
    use moveos_std::object::ObjectID;
    use moveos_std::context::Context;
    use rooch_examples::article;
    use rooch_examples::article_add_comment_logic;
    use rooch_examples::article_create_logic;
    use rooch_examples::article_delete_logic;
    use rooch_examples::article_remove_comment_logic;
    use rooch_examples::article_update_comment_logic;
    use rooch_examples::article_update_logic;
    use std::string::String;

    public entry fun update_comment(
        ctx: &mut Context,
        account: &signer,
        id: ObjectID,
        comment_seq_id: u64,
        commenter: String,
        body: String,
        owner: address,
    ) {
        let article_obj = article::get_article(ctx, id);
        let comment_updated = article_update_comment_logic::verify(
            ctx,
            account,
            comment_seq_id,
            commenter,
            body,
            owner,
            &article_obj,
        );
        let updated_article_obj = article_update_comment_logic::mutate(
            ctx,
            account,
            &comment_updated,
            article_obj,
        );
        article::update_version_and_add(ctx, updated_article_obj);
        article::emit_comment_updated(ctx, comment_updated);
    }

    public entry fun remove_comment(
        ctx: &mut Context,
        account: &signer,
        id: ObjectID,
        comment_seq_id: u64,
    ) {
        let article_obj = article::get_article(ctx, id);
        let comment_removed = article_remove_comment_logic::verify(
            ctx,
            account,
            comment_seq_id,
            &article_obj,
        );
        let updated_article_obj = article_remove_comment_logic::mutate(
            ctx,
            account,
            &comment_removed,
            article_obj,
        );
        article::update_version_and_add(ctx, updated_article_obj);
        article::emit_comment_removed(ctx, comment_removed);
    }

    public entry fun add_comment(
        ctx: &mut Context,
        account: &signer,
        id: ObjectID,
        commenter: String,
        body: String,
    ) {
        let article_obj = article::get_article(ctx, id);
        let comment_added = article_add_comment_logic::verify(
            ctx,
            account,
            commenter,
            body,
            &article_obj,
        );
        let updated_article_obj = article_add_comment_logic::mutate(
            ctx,
            account,
            &comment_added,
            article_obj,
        );
        article::update_version_and_add(ctx, updated_article_obj);
        article::emit_comment_added(ctx, comment_added);
    }

    public entry fun create(
        ctx: &mut Context,
        account: &signer,
        title: String,
        body: String,
    ) {
        let article_created = article_create_logic::verify(
            ctx,
            account,
            title,
            body,
        );
        let article_obj = article_create_logic::mutate(
            ctx,
            account,
            &article_created,
        );
        article::set_article_created_id(&mut article_created, article::id(&article_obj));
        article::add_article(ctx, article_obj);
        article::emit_article_created(ctx, article_created);
    }

    public entry fun update(
        ctx: &mut Context,
        account: &signer,
        id: ObjectID,
        title: String,
        body: String,
    ) {
        let article_obj = article::get_article(ctx, id);
        let article_updated = article_update_logic::verify(
            ctx,
            account,
            title,
            body,
            &article_obj,
        );
        let updated_article_obj = article_update_logic::mutate(
            ctx,
            account,
            &article_updated,
            article_obj,
        );
        article::update_version_and_add(ctx, updated_article_obj);
        article::emit_article_updated(ctx, article_updated);
    }

    public entry fun delete(
        ctx: &mut Context,
        account: &signer,
        id: ObjectID,
    ) {
        let article_obj = article::get_article(ctx, id);
        let article_deleted = article_delete_logic::verify(
            ctx,
            account,
            &article_obj,
        );
        let updated_article_obj = article_delete_logic::mutate(
            ctx,
            account,
            &article_deleted,
            article_obj,
        );
        article::drop_article(updated_article_obj);
        article::emit_article_deleted(ctx, article_deleted);
    }

}
