// Copyright (c) RoochNetwork
// SPDX-License-Identifier: Apache-2.0

// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module rooch_examples::blog_created {

    use rooch_examples::blog::{Self, BlogCreated};
    use std::string::String;

    public fun name(blog_created: &BlogCreated): String {
        blog::blog_created_name(blog_created)
    }

}
