// Copyright (c) RoochNetwork
// SPDX-License-Identifier: Apache-2.0

// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module rooch_examples::comment_added {

    use moveos_std::object_id::ObjectID;
    use rooch_examples::article::{Self, CommentAdded};
    use std::string::String;

    public fun id(comment_added: &CommentAdded): ObjectID {
        article::comment_added_id(comment_added)
    }

    public fun comment_seq_id(comment_added: &CommentAdded): u64 {
        article::comment_added_comment_seq_id(comment_added)
    }

    public fun commenter(comment_added: &CommentAdded): String {
        article::comment_added_commenter(comment_added)
    }

    public fun body(comment_added: &CommentAdded): String {
        article::comment_added_body(comment_added)
    }

    public fun owner(comment_added: &CommentAdded): address {
        article::comment_added_owner(comment_added)
    }

}
