[package]
name = "RoochFramework"
version = "0.0.1"

[addresses]
std = "0x1"
moveos_std = "0x1"
rooch_framework = "0x1"
vm_reserved = "0x0"

[dependencies]
MoveosStdLib = { local = "../moveos-stdlib" }
