[package]
name = "MosStdLib"
version = "0.0.1"

[addresses]
std = "0x1"
mos_std = "0x1"

[dependencies]
#MoveStdlib = { local = "../move-stdlib" }
MoveStdlib = { git = "https://github.com/rooch-network/move.git", subdir = "language/move-stdlib", rev = "5b413d009515ad1144042ded27cbe9bd702aaad7" }
MoveNursery = { git = "https://github.com/rooch-network/move.git", subdir = "language/move-stdlib/nursery", rev = "5b413d009515ad1144042ded27cbe9bd702aaad7" }