apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
    spec:
      serviceAccountName: promtail-sa
      containers:
      - name: promtail
        image: grafana/promtail:latest
        volumeMounts:
          - name: config-volume
            mountPath: /etc/promtail
          - name: loki-ip-volume
            mountPath: /etc/loki-ip
          - name: varlog
            mountPath: /var/log
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
            readOnly: true
        args:
          - -config.file=/etc/promtail/promtail.yaml
          - -config.expand-env=true
        env:
          - name: Loki_IP
            valueFrom:
              secretKeyRef:
                name: loki-ip-secret
                key: loki-ip
          - name: 'HOSTNAME' # needed when using kubernetes_sd_configs
            valueFrom:
              fieldRef:
                fieldPath: 'spec.nodeName'
      volumes:
        - name: config-volume
          configMap:
            name: promtail-config
        - name: loki-ip-volume
          secret:
            secretName: loki-ip-secret
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
