apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mainnet-tweet-fetch-schedule-data
  namespace: mainnet
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi