[package]
name = "complex_struct"
version = "0.0.1"

[dependencies]
MoveosStdLib = { local = "../../moveos/moveos-stdlib/moveos-stdlib" }

[addresses]
rooch_examples =  "_"
moveos_std =  "0x1"
rooch_framework =  "0x1"

[dev-addresses]
rooch_examples = "0x42"