// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.3
// source: proto/finalitygadget.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BlockInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// block_hash is the hash of the block
	BlockHash string `protobuf:"bytes,1,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	// block_height is the height of the block
	BlockHeight uint64 `protobuf:"varint,2,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	// block_timestamp is the unix timestamp of the block
	BlockTimestamp uint64 `protobuf:"varint,3,opt,name=block_timestamp,json=blockTimestamp,proto3" json:"block_timestamp,omitempty"`
}

func (x *BlockInfo) Reset() {
	*x = BlockInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_finalitygadget_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockInfo) ProtoMessage() {}

func (x *BlockInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_finalitygadget_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockInfo.ProtoReflect.Descriptor instead.
func (*BlockInfo) Descriptor() ([]byte, []int) {
	return file_proto_finalitygadget_proto_rawDescGZIP(), []int{0}
}

func (x *BlockInfo) GetBlockHash() string {
	if x != nil {
		return x.BlockHash
	}
	return ""
}

func (x *BlockInfo) GetBlockHeight() uint64 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

func (x *BlockInfo) GetBlockTimestamp() uint64 {
	if x != nil {
		return x.BlockTimestamp
	}
	return 0
}

type QueryIsBlockBabylonFinalizedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Block *BlockInfo `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
}

func (x *QueryIsBlockBabylonFinalizedRequest) Reset() {
	*x = QueryIsBlockBabylonFinalizedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_finalitygadget_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryIsBlockBabylonFinalizedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryIsBlockBabylonFinalizedRequest) ProtoMessage() {}

func (x *QueryIsBlockBabylonFinalizedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_finalitygadget_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryIsBlockBabylonFinalizedRequest.ProtoReflect.Descriptor instead.
func (*QueryIsBlockBabylonFinalizedRequest) Descriptor() ([]byte, []int) {
	return file_proto_finalitygadget_proto_rawDescGZIP(), []int{1}
}

func (x *QueryIsBlockBabylonFinalizedRequest) GetBlock() *BlockInfo {
	if x != nil {
		return x.Block
	}
	return nil
}

type QueryBlockRangeBabylonFinalizedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Blocks []*BlockInfo `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`
}

func (x *QueryBlockRangeBabylonFinalizedRequest) Reset() {
	*x = QueryBlockRangeBabylonFinalizedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_finalitygadget_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryBlockRangeBabylonFinalizedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryBlockRangeBabylonFinalizedRequest) ProtoMessage() {}

func (x *QueryBlockRangeBabylonFinalizedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_finalitygadget_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryBlockRangeBabylonFinalizedRequest.ProtoReflect.Descriptor instead.
func (*QueryBlockRangeBabylonFinalizedRequest) Descriptor() ([]byte, []int) {
	return file_proto_finalitygadget_proto_rawDescGZIP(), []int{2}
}

func (x *QueryBlockRangeBabylonFinalizedRequest) GetBlocks() []*BlockInfo {
	if x != nil {
		return x.Blocks
	}
	return nil
}

type QueryBlockRangeBabylonFinalizedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// last_finalized_block_height is the height of the last finalized block
	LastFinalizedBlockHeight uint64 `protobuf:"varint,1,opt,name=last_finalized_block_height,json=lastFinalizedBlockHeight,proto3" json:"last_finalized_block_height,omitempty"`
}

func (x *QueryBlockRangeBabylonFinalizedResponse) Reset() {
	*x = QueryBlockRangeBabylonFinalizedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_finalitygadget_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryBlockRangeBabylonFinalizedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryBlockRangeBabylonFinalizedResponse) ProtoMessage() {}

func (x *QueryBlockRangeBabylonFinalizedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_finalitygadget_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryBlockRangeBabylonFinalizedResponse.ProtoReflect.Descriptor instead.
func (*QueryBlockRangeBabylonFinalizedResponse) Descriptor() ([]byte, []int) {
	return file_proto_finalitygadget_proto_rawDescGZIP(), []int{3}
}

func (x *QueryBlockRangeBabylonFinalizedResponse) GetLastFinalizedBlockHeight() uint64 {
	if x != nil {
		return x.LastFinalizedBlockHeight
	}
	return 0
}

type QueryBtcStakingActivatedTimestampRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *QueryBtcStakingActivatedTimestampRequest) Reset() {
	*x = QueryBtcStakingActivatedTimestampRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_finalitygadget_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryBtcStakingActivatedTimestampRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryBtcStakingActivatedTimestampRequest) ProtoMessage() {}

func (x *QueryBtcStakingActivatedTimestampRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_finalitygadget_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryBtcStakingActivatedTimestampRequest.ProtoReflect.Descriptor instead.
func (*QueryBtcStakingActivatedTimestampRequest) Descriptor() ([]byte, []int) {
	return file_proto_finalitygadget_proto_rawDescGZIP(), []int{4}
}

type QueryBtcStakingActivatedTimestampResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// timestamp is the unix timestamp when BTC staking was activated
	ActivatedTimestamp uint64 `protobuf:"varint,1,opt,name=activated_timestamp,json=activatedTimestamp,proto3" json:"activated_timestamp,omitempty"`
}

func (x *QueryBtcStakingActivatedTimestampResponse) Reset() {
	*x = QueryBtcStakingActivatedTimestampResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_finalitygadget_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryBtcStakingActivatedTimestampResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryBtcStakingActivatedTimestampResponse) ProtoMessage() {}

func (x *QueryBtcStakingActivatedTimestampResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_finalitygadget_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryBtcStakingActivatedTimestampResponse.ProtoReflect.Descriptor instead.
func (*QueryBtcStakingActivatedTimestampResponse) Descriptor() ([]byte, []int) {
	return file_proto_finalitygadget_proto_rawDescGZIP(), []int{5}
}

func (x *QueryBtcStakingActivatedTimestampResponse) GetActivatedTimestamp() uint64 {
	if x != nil {
		return x.ActivatedTimestamp
	}
	return 0
}

type QueryIsBlockFinalizedByHeightRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// block_height is the height of the block
	BlockHeight uint64 `protobuf:"varint,1,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
}

func (x *QueryIsBlockFinalizedByHeightRequest) Reset() {
	*x = QueryIsBlockFinalizedByHeightRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_finalitygadget_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryIsBlockFinalizedByHeightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryIsBlockFinalizedByHeightRequest) ProtoMessage() {}

func (x *QueryIsBlockFinalizedByHeightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_finalitygadget_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryIsBlockFinalizedByHeightRequest.ProtoReflect.Descriptor instead.
func (*QueryIsBlockFinalizedByHeightRequest) Descriptor() ([]byte, []int) {
	return file_proto_finalitygadget_proto_rawDescGZIP(), []int{6}
}

func (x *QueryIsBlockFinalizedByHeightRequest) GetBlockHeight() uint64 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

type QueryIsBlockFinalizedByHashRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// block_hash is the hash of the block
	BlockHash string `protobuf:"bytes,1,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
}

func (x *QueryIsBlockFinalizedByHashRequest) Reset() {
	*x = QueryIsBlockFinalizedByHashRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_finalitygadget_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryIsBlockFinalizedByHashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryIsBlockFinalizedByHashRequest) ProtoMessage() {}

func (x *QueryIsBlockFinalizedByHashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_finalitygadget_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryIsBlockFinalizedByHashRequest.ProtoReflect.Descriptor instead.
func (*QueryIsBlockFinalizedByHashRequest) Descriptor() ([]byte, []int) {
	return file_proto_finalitygadget_proto_rawDescGZIP(), []int{7}
}

func (x *QueryIsBlockFinalizedByHashRequest) GetBlockHash() string {
	if x != nil {
		return x.BlockHash
	}
	return ""
}

type QueryIsBlockFinalizedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// is_finalized is true if the block is finalized
	IsFinalized bool `protobuf:"varint,1,opt,name=is_finalized,json=isFinalized,proto3" json:"is_finalized,omitempty"`
}

func (x *QueryIsBlockFinalizedResponse) Reset() {
	*x = QueryIsBlockFinalizedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_finalitygadget_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryIsBlockFinalizedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryIsBlockFinalizedResponse) ProtoMessage() {}

func (x *QueryIsBlockFinalizedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_finalitygadget_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryIsBlockFinalizedResponse.ProtoReflect.Descriptor instead.
func (*QueryIsBlockFinalizedResponse) Descriptor() ([]byte, []int) {
	return file_proto_finalitygadget_proto_rawDescGZIP(), []int{8}
}

func (x *QueryIsBlockFinalizedResponse) GetIsFinalized() bool {
	if x != nil {
		return x.IsFinalized
	}
	return false
}

type QueryLatestFinalizedBlockRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *QueryLatestFinalizedBlockRequest) Reset() {
	*x = QueryLatestFinalizedBlockRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_finalitygadget_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryLatestFinalizedBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryLatestFinalizedBlockRequest) ProtoMessage() {}

func (x *QueryLatestFinalizedBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_finalitygadget_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryLatestFinalizedBlockRequest.ProtoReflect.Descriptor instead.
func (*QueryLatestFinalizedBlockRequest) Descriptor() ([]byte, []int) {
	return file_proto_finalitygadget_proto_rawDescGZIP(), []int{9}
}

type QueryBlockResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Block *BlockInfo `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
}

func (x *QueryBlockResponse) Reset() {
	*x = QueryBlockResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_finalitygadget_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryBlockResponse) ProtoMessage() {}

func (x *QueryBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_finalitygadget_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryBlockResponse.ProtoReflect.Descriptor instead.
func (*QueryBlockResponse) Descriptor() ([]byte, []int) {
	return file_proto_finalitygadget_proto_rawDescGZIP(), []int{10}
}

func (x *QueryBlockResponse) GetBlock() *BlockInfo {
	if x != nil {
		return x.Block
	}
	return nil
}

var File_proto_finalitygadget_proto protoreflect.FileDescriptor

var file_proto_finalitygadget_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x66, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x74, 0x79,
	0x67, 0x61, 0x64, 0x67, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x76, 0x0a, 0x09, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x61, 0x73, 0x68, 0x12,
	0x21, 0x0a, 0x0c, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x65, 0x69, 0x67,
	0x68, 0x74, 0x12, 0x27, 0x0a, 0x0f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0e, 0x62, 0x6c, 0x6f,
	0x63, 0x6b, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x4d, 0x0a, 0x23, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x49, 0x73, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x42, 0x61, 0x62, 0x79, 0x6c,
	0x6f, 0x6e, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x26, 0x0a, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x22, 0x52, 0x0a, 0x26, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x42, 0x61, 0x62,
	0x79, 0x6c, 0x6f, 0x6e, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x06, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x6c, 0x6f,
	0x63, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x22, 0x68,
	0x0a, 0x27, 0x51, 0x75, 0x65, 0x72, 0x79, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x61, 0x6e, 0x67,
	0x65, 0x42, 0x61, 0x62, 0x79, 0x6c, 0x6f, 0x6e, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x1b, 0x6c, 0x61, 0x73,
	0x74, 0x5f, 0x66, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x5f, 0x62, 0x6c, 0x6f, 0x63,
	0x6b, 0x5f, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x18,
	0x6c, 0x61, 0x73, 0x74, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x42, 0x6c, 0x6f,
	0x63, 0x6b, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x22, 0x2a, 0x0a, 0x28, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x42, 0x74, 0x63, 0x53, 0x74, 0x61, 0x6b, 0x69, 0x6e, 0x67, 0x41, 0x63, 0x74, 0x69, 0x76,
	0x61, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x5c, 0x0a, 0x29, 0x51, 0x75, 0x65, 0x72, 0x79, 0x42, 0x74, 0x63,
	0x53, 0x74, 0x61, 0x6b, 0x69, 0x6e, 0x67, 0x41, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x64,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2f, 0x0a, 0x13, 0x61, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x12,
	0x61, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x22, 0x49, 0x0a, 0x24, 0x51, 0x75, 0x65, 0x72, 0x79, 0x49, 0x73, 0x42, 0x6c, 0x6f,
	0x63, 0x6b, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x42, 0x79, 0x48, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x62, 0x6c,
	0x6f, 0x63, 0x6b, 0x5f, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x0b, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x22, 0x43, 0x0a,
	0x22, 0x51, 0x75, 0x65, 0x72, 0x79, 0x49, 0x73, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x46, 0x69, 0x6e,
	0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x42, 0x79, 0x48, 0x61, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x68, 0x61, 0x73,
	0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x61,
	0x73, 0x68, 0x22, 0x42, 0x0a, 0x1d, 0x51, 0x75, 0x65, 0x72, 0x79, 0x49, 0x73, 0x42, 0x6c, 0x6f,
	0x63, 0x6b, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x69, 0x73, 0x5f, 0x66, 0x69, 0x6e, 0x61, 0x6c, 0x69,
	0x7a, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x69, 0x73, 0x46, 0x69, 0x6e,
	0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x22, 0x22, 0x0a, 0x20, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4c,
	0x61, 0x74, 0x65, 0x73, 0x74, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x3c, 0x0a, 0x12, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x26, 0x0a, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x32, 0xd3, 0x05, 0x0a, 0x0e, 0x46, 0x69, 0x6e,
	0x61, 0x6c, 0x69, 0x74, 0x79, 0x47, 0x61, 0x64, 0x67, 0x65, 0x74, 0x12, 0x70, 0x0a, 0x1c, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x49, 0x73, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x42, 0x61, 0x62, 0x79, 0x6c,
	0x6f, 0x6e, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x12, 0x2a, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x49, 0x73, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x42, 0x61, 0x62, 0x79, 0x6c, 0x6f, 0x6e, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x49, 0x73, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x46, 0x69, 0x6e, 0x61,
	0x6c, 0x69, 0x7a, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x80, 0x01,
	0x0a, 0x1f, 0x51, 0x75, 0x65, 0x72, 0x79, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x61, 0x6e, 0x67,
	0x65, 0x42, 0x61, 0x62, 0x79, 0x6c, 0x6f, 0x6e, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65,
	0x64, 0x12, 0x2d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x42, 0x61, 0x62, 0x79, 0x6c, 0x6f, 0x6e,
	0x46, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x2e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x42, 0x61, 0x62, 0x79, 0x6c, 0x6f, 0x6e, 0x46,
	0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x86, 0x01, 0x0a, 0x21, 0x51, 0x75, 0x65, 0x72, 0x79, 0x42, 0x74, 0x63, 0x53, 0x74, 0x61,
	0x6b, 0x69, 0x6e, 0x67, 0x41, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x2f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x42, 0x74, 0x63, 0x53, 0x74, 0x61, 0x6b, 0x69, 0x6e, 0x67, 0x41, 0x63,
	0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x30, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x42, 0x74, 0x63, 0x53, 0x74, 0x61, 0x6b, 0x69, 0x6e, 0x67, 0x41,
	0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x72, 0x0a, 0x1d, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x49, 0x73, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a,
	0x65, 0x64, 0x42, 0x79, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x2b, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x49, 0x73, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x46,
	0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x42, 0x79, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x49, 0x73, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x46, 0x69, 0x6e, 0x61,
	0x6c, 0x69, 0x7a, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6e, 0x0a,
	0x1b, 0x51, 0x75, 0x65, 0x72, 0x79, 0x49, 0x73, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x46, 0x69, 0x6e,
	0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x42, 0x79, 0x48, 0x61, 0x73, 0x68, 0x12, 0x29, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x49, 0x73, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x42, 0x79, 0x48, 0x61, 0x73, 0x68,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x49, 0x73, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x46, 0x69, 0x6e, 0x61,
	0x6c, 0x69, 0x7a, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5f, 0x0a,
	0x19, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x46, 0x69, 0x6e, 0x61,
	0x6c, 0x69, 0x7a, 0x65, 0x64, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x27, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x46, 0x69,
	0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x31,
	0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x61, 0x62,
	0x79, 0x6c, 0x6f, 0x6e, 0x6c, 0x61, 0x62, 0x73, 0x2d, 0x69, 0x6f, 0x2f, 0x66, 0x69, 0x6e, 0x61,
	0x6c, 0x69, 0x74, 0x79, 0x2d, 0x67, 0x61, 0x64, 0x67, 0x65, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_finalitygadget_proto_rawDescOnce sync.Once
	file_proto_finalitygadget_proto_rawDescData = file_proto_finalitygadget_proto_rawDesc
)

func file_proto_finalitygadget_proto_rawDescGZIP() []byte {
	file_proto_finalitygadget_proto_rawDescOnce.Do(func() {
		file_proto_finalitygadget_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_finalitygadget_proto_rawDescData)
	})
	return file_proto_finalitygadget_proto_rawDescData
}

var file_proto_finalitygadget_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_finalitygadget_proto_goTypes = []interface{}{
	(*BlockInfo)(nil), // 0: proto.BlockInfo
	(*QueryIsBlockBabylonFinalizedRequest)(nil),       // 1: proto.QueryIsBlockBabylonFinalizedRequest
	(*QueryBlockRangeBabylonFinalizedRequest)(nil),    // 2: proto.QueryBlockRangeBabylonFinalizedRequest
	(*QueryBlockRangeBabylonFinalizedResponse)(nil),   // 3: proto.QueryBlockRangeBabylonFinalizedResponse
	(*QueryBtcStakingActivatedTimestampRequest)(nil),  // 4: proto.QueryBtcStakingActivatedTimestampRequest
	(*QueryBtcStakingActivatedTimestampResponse)(nil), // 5: proto.QueryBtcStakingActivatedTimestampResponse
	(*QueryIsBlockFinalizedByHeightRequest)(nil),      // 6: proto.QueryIsBlockFinalizedByHeightRequest
	(*QueryIsBlockFinalizedByHashRequest)(nil),        // 7: proto.QueryIsBlockFinalizedByHashRequest
	(*QueryIsBlockFinalizedResponse)(nil),             // 8: proto.QueryIsBlockFinalizedResponse
	(*QueryLatestFinalizedBlockRequest)(nil),          // 9: proto.QueryLatestFinalizedBlockRequest
	(*QueryBlockResponse)(nil),                        // 10: proto.QueryBlockResponse
}
var file_proto_finalitygadget_proto_depIdxs = []int32{
	0,  // 0: proto.QueryIsBlockBabylonFinalizedRequest.block:type_name -> proto.BlockInfo
	0,  // 1: proto.QueryBlockRangeBabylonFinalizedRequest.blocks:type_name -> proto.BlockInfo
	0,  // 2: proto.QueryBlockResponse.block:type_name -> proto.BlockInfo
	1,  // 3: proto.FinalityGadget.QueryIsBlockBabylonFinalized:input_type -> proto.QueryIsBlockBabylonFinalizedRequest
	2,  // 4: proto.FinalityGadget.QueryBlockRangeBabylonFinalized:input_type -> proto.QueryBlockRangeBabylonFinalizedRequest
	4,  // 5: proto.FinalityGadget.QueryBtcStakingActivatedTimestamp:input_type -> proto.QueryBtcStakingActivatedTimestampRequest
	6,  // 6: proto.FinalityGadget.QueryIsBlockFinalizedByHeight:input_type -> proto.QueryIsBlockFinalizedByHeightRequest
	7,  // 7: proto.FinalityGadget.QueryIsBlockFinalizedByHash:input_type -> proto.QueryIsBlockFinalizedByHashRequest
	9,  // 8: proto.FinalityGadget.QueryLatestFinalizedBlock:input_type -> proto.QueryLatestFinalizedBlockRequest
	8,  // 9: proto.FinalityGadget.QueryIsBlockBabylonFinalized:output_type -> proto.QueryIsBlockFinalizedResponse
	3,  // 10: proto.FinalityGadget.QueryBlockRangeBabylonFinalized:output_type -> proto.QueryBlockRangeBabylonFinalizedResponse
	5,  // 11: proto.FinalityGadget.QueryBtcStakingActivatedTimestamp:output_type -> proto.QueryBtcStakingActivatedTimestampResponse
	8,  // 12: proto.FinalityGadget.QueryIsBlockFinalizedByHeight:output_type -> proto.QueryIsBlockFinalizedResponse
	8,  // 13: proto.FinalityGadget.QueryIsBlockFinalizedByHash:output_type -> proto.QueryIsBlockFinalizedResponse
	10, // 14: proto.FinalityGadget.QueryLatestFinalizedBlock:output_type -> proto.QueryBlockResponse
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_finalitygadget_proto_init() }
func file_proto_finalitygadget_proto_init() {
	if File_proto_finalitygadget_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_finalitygadget_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_finalitygadget_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryIsBlockBabylonFinalizedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_finalitygadget_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryBlockRangeBabylonFinalizedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_finalitygadget_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryBlockRangeBabylonFinalizedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_finalitygadget_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryBtcStakingActivatedTimestampRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_finalitygadget_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryBtcStakingActivatedTimestampResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_finalitygadget_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryIsBlockFinalizedByHeightRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_finalitygadget_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryIsBlockFinalizedByHashRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_finalitygadget_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryIsBlockFinalizedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_finalitygadget_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryLatestFinalizedBlockRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_finalitygadget_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryBlockResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_finalitygadget_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_finalitygadget_proto_goTypes,
		DependencyIndexes: file_proto_finalitygadget_proto_depIdxs,
		MessageInfos:      file_proto_finalitygadget_proto_msgTypes,
	}.Build()
	File_proto_finalitygadget_proto = out.File
	file_proto_finalitygadget_proto_rawDesc = nil
	file_proto_finalitygadget_proto_goTypes = nil
	file_proto_finalitygadget_proto_depIdxs = nil
}
