// Copyright (c) RoochNetwork
// SPDX-License-Identifier: Apache-2.0

// This file is @generated by prost-build.
pub mod proto {
    include!("proto.rs");
}

// pub mod proto;

// include!(concat!(env!("OUT_DIR"), "/mod.rs"));
