[package]
name = "timeout-join-handler"

# Workspace inherited keys
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
thiserror = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }