apiVersion: apps/v1
kind: Deployment
metadata:
  name: testnet-oracle-okx
  namespace: testnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testnet-oracle-okx
  template:
    metadata:
      labels:
        app: testnet-oracle-okx
    spec:
      initContainers:
      - name: init-rooch
        image: ghcr.io/rooch-network/rooch:main
        command: ["/bin/sh", "-c"]
        args:
        - |
          if [ ! -f /root/.rooch/initialized ]; then
            /rooch/rooch init -m "${INIT_SECRET}" --skip-password
            /rooch/rooch env switch --alias test
            /rooch/rooch account create
            /rooch/rooch account create
            /rooch/rooch account create
            ls -la /root/.rooch/rooch_config/
            touch /root/.rooch/initialized
          fi
        env:
        - name: INIT_SECRET
          valueFrom:
            secretKeyRef:
              name: rooch-faucet-secrets
              key: init-phrase
        volumeMounts:
        - name: rooch-data
          mountPath: /root
      containers:
      - name: rooch-faucet
        image: ghcr.io/rooch-network/rooch:main
        command: ["/rooch/rooch"]
        args: 
        - "oracle"
        - "report"
        - "--oracle-id"
        - ""
        - "--oracle-admin-id"
        - ""
        - "--data-source"
        - "okx"
        - "--ticker"
        - "btcusd"
        - "--aggregate-strategy"
        - "--report-interval"
        - "10"
        volumeMounts:
        - name: rooch-data
          mountPath: /root
      volumes:
      - name: rooch-data
        persistentVolumeClaim:
          claimName: testnet-oracle-okx-data