inputs:
  GIT_CREDENTIALS:
    description: "Optional credentials to pass to git"
    required: false

runs:
  using: composite
  steps:
    - run: sudo apt-get update && sudo apt-get install build-essential ca-certificates clang curl git libpq-dev libssl-dev pkg-config lsof lld --no-install-recommends --assume-yes
      shell: bash

    - uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # pin@v1
      with:
        override: true
        components: rustfmt, clippy
    - uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: ap-northeast-1
      secrets:
        AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
    # https://github.com/Mozilla-Actions/sccache-action
    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.3
      env:
        SCCACHE_GHA_ENABLED: "true"
        RUSTC_WRAPPER: "sccache"
        SCCACHE_BUCKET: "rooch-gha-cache"
        SCCACHE_REGION: "ap-northeast-1"
        SCCACHE_S3_USE_SSL: "true"
      secrets:
        AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"

    - name: install protoc and related tools
      shell: bash
      run: scripts/dev_setup.sh -b -r


