inputs:
  GIT_CREDENTIALS:
    description: "Optional credentials to pass to git"
    required: false

runs:
  using: composite
  steps:
    - run: sudo apt-get update && sudo apt-get install build-essential ca-certificates clang curl git libpq-dev libssl-dev pkg-config lsof lld --no-install-recommends --assume-yes
      shell: bash

    - uses: actions-rs/toolchain@v1.0.6
      with:
        override: true
        components: rustfmt, clippy

    - name: install protoc and related tools
      shell: bash
      run: scripts/dev_setup.sh -b -r
