[package]
name = "moveos-config"
version = "0.5.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true }
serde_yaml = { workspace = true }
serde_with = { workspace = true }
thiserror = { workspace = true }
tonic = { workspace = true }
coerce = { workspace = true }
dirs  = { workspace = true }
once_cell  = { workspace = true }
clap  = { workspace = true }
tempfile  = { workspace = true }
