[package]
name = "rooch-oracle"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
tokio-tungstenite = { workspace = true }
tungstenite = { workspace = true }
serde_json = { workspace = true }
futures-util = { workspace = true }
tracing-subscriber = { workspace = true }
log = { workspace = true }
clap = { workspace = true }
reqwest = { workspace = true }
anyhow = { workspace = true }
bcs = { workspace = true }

rooch-rpc-api = { workspace = true }
move-core-types = {  workspace = true }
moveos-types = { workspace = true }
rooch-types = {  workspace = true }
rooch-rpc-client = {  workspace = true }
