[package]
name = "btc_blind_box"
version = "0.0.1"

[dependencies]
MoveosStdlib = { local = "../../frameworks/moveos-stdlib" }
RoochFramework = { local = "../../frameworks/rooch-framework" }
BitcoinMove = { local = "../../frameworks/bitcoin-move" }

[addresses]
btc_blind_box =  "_"
moveos_std =  "0x2"
rooch_framework =  "0x3"
bitcoin_move =  "0x4"

[dev-addresses]
btc_blind_box = "0x42"