[package]
name = "minter_manager"
version = "0.0.1"

[dependencies]
MoveStdlib = { local = "../../frameworks/move-stdlib" }
MoveosStdlib = { local = "../../frameworks/moveos-stdlib" }
RoochFramework = { local = "../../frameworks/rooch-framework" }
app_admin = { local = "../app_admin" }

[addresses]
std = "0x1"
moveos_std = "0x2"
rooch_framework = "0x3"
minter_manager = "_"
app_admin = "_"