[package]
name = "grow_registration"
version = "0.0.1"

[dependencies]
MoveosStdlib = { local = "../../frameworks/moveos-stdlib" }
RoochFramework = { local = "../../frameworks/rooch-framework" }
BitcoinMove = { local = "../../frameworks/bitcoin-move" }
grow_bitcoin = { local = "../../apps/grow_bitcoin" }

[addresses]
grow_registration = "0x701c21bf1c8cd5af8c42983890d8ca55e7a820171b8e744c13f2d9998bf76cc3"
std = "0x1"
moveos_std = "0x2"
rooch_framework = "0x3"
app_admin = "0x701c21bf1c8cd5af8c42983890d8ca55e7a820171b8e744c13f2d9998bf76cc3"
grow_bitcoin = "0x701c21bf1c8cd5af8c42983890d8ca55e7a820171b8e744c13f2d9998bf76cc3"
