[package]
name = "grow_registration"
version = "0.0.1"

[dependencies]
MoveosStdlib = { local = "../../frameworks/moveos-stdlib" }
RoochFramework = { local = "../../frameworks/rooch-framework" }
BitcoinMove = { local = "../../frameworks/bitcoin-move" }
grow_bitcoin = { local = "../../apps/grow_bitcoin" }

[addresses]
grow_registration = "_"
std = "0x1"
moveos_std = "0x2"
rooch_framework = "0x3"
app_admin = "_"
grow_bitcoin = "_"
