name: Cleanup
on:
  pull_request:
    types:
      - closed

jobs:
  cleanup:
    name: Cleanup
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Cleanup Cache
        uses: actions/github-script@v7
        with:
          retries: 3
          retry-exempt-status-codes: 400,401
          script: |
            const branch = `refs/pull/${{ github.event.pull_request.number }}/merge`;
            const caches = await github.rest.actions.getActionsCacheList({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: branch
            });
            if (!caches.data.actions_caches.length) {
              console.log(`No caches found for branch ${branch}`);
              return;
            }
            for (const cache of caches.data.actions_caches) {
              console.log(`Deleting cache with id ${cache.id}...`);
              await github.rest.actions.deleteActionsCacheById({
                owner: context.repo.owner,
                repo: context.repo.repo,
                cache_id: cache.id
              });
            }
            console.log('Cache cleanup complete');
