name: Deploy Portal Frontend

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Deploy to GCP VM
      env:
        PRIVATE_KEY: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.GCP_VM_HOST }}
        USER: ${{ secrets.GCP_VM_USER }}
      run: |
        echo "$PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST "cd /root/rooch && git pull origin main && pnpm install && pnpm rooch-sdk gen && pnpm rooch-sdk build && pnpm rooch-sdk-kit build && pnpm rooch-portal build && cd /root/rooch/rooch-portal-v1 && gsutil rsync -r out gs://rooch_portal"
